spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ORDERMANAGEMENT
    username: postgres
    password: confidencial

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
    hibernate:
      ddl-auto: none
 
server:
  port: 9050